/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.conversao;

/**
 *
 * @author Aluno
 */
public class conversor extends javax.swing.JFrame {

    /**
     * Creates new form conversor
     */
    public conversor() {
        initComponents();
    }
    Double valor1, resultado;
    String comprimento1, comprimento2;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        result = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Conversor de comprimento");

        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Para");

        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });

        jButton1.setText("Resultado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quilometro", "Metro", "Decimetro", "Centimetro", "Milimetro" }));
        jComboBox3.setSelectedItem(jComboBox3);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quilometro", "Metro", "Decimetro", "Centimetro", "Milimetro" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(124, 124, 124))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        valor1 = Double.parseDouble(numero.getText());
        comprimento1 = jComboBox3.getSelectedItem().toString();
        comprimento2 = jComboBox4.getSelectedItem().toString();

        if(comprimento1 == "Quilometro" && comprimento2 == "Metro"){
                         
            resultado = valor1 * 1000;
            result.setText(String.valueOf(resultado));
                
        }else if(comprimento1 == "Quilometro" && comprimento2 == "Decimetro"){    
                
            resultado = valor1 * 10000;
            result.setText(String.valueOf(resultado));
            
        }else if(comprimento1 == "Quilometro" && comprimento2 == "Centimetro"){
                
            resultado = valor1 * 100000;
            result.setText(String.valueOf(resultado));
                
        }else if(comprimento1 == "Quilometro" && comprimento2 == "Milimetro"){
                
            resultado = valor1 * 1000000;
            result.setText(String.valueOf(resultado));
            
        }else if(comprimento1 == "Quilometro" && comprimento2 == "Quilometro"){
            
            resultado = valor1 * 1;
            result.setText(String.valueOf(resultado));
        
        
        }else if(comprimento1 == "Metro" && comprimento2 == "Quilometro"){
                
            resultado = valor1 / 0.001;
            result.setText(String.valueOf(resultado));
                 
        }else if(comprimento1 == "Metro" && comprimento2 == "Decimetro"){
                
            resultado = valor1 * 10;
            result.setText(String.valueOf(resultado));
                 
                
        }else if(comprimento1 == "Metro" && comprimento2 == "Centimetro"){
                
            resultado = valor1 * 100;
            result.setText(String.valueOf(resultado));
                 
                
        }else if(comprimento1 == "Metro" && comprimento2 == "Milimetro"){
                
            resultado = valor1 * 1000;
            result.setText(String.valueOf(resultado));
            
        }else if(comprimento1 == "Metro" && comprimento2 == "Metro"){
            
            resultado = valor1 * 1;
            result.setText(String.valueOf(resultado));
        
        }else if(comprimento1 == "Decimetro" && comprimento2 == "Metro"){
                 
            resultado = valor1 / 0.1;
            result.setText(String.valueOf(resultado));
                
        }else if(comprimento1 == "Decimetro" && comprimento2 == "Quilometro"){
                
            resultado = valor1 / 0.0001;
            result.setText(String.valueOf(resultado));
                 
        }else if(comprimento1 == "Decimetro" && comprimento2 == "Centimetro"){
                
            resultado = valor1 * 10;
            result.setText(String.valueOf(resultado));
                 
        }else if(comprimento1 == "Decimetro" && comprimento2 == "Milimetro"){
                
            resultado = valor1 * 100;
            result.setText(String.valueOf(resultado));
            
        }else if(comprimento1 == "Decimetro" && comprimento2 == "Decimetro"){
            
            resultado = valor1 * 1;
            result.setText(String.valueOf(resultado));
        
        }else if(comprimento1 == "Centimetro" && comprimento2 == "Metro"){
                   
            resultado = valor1 / 0.01;
            result.setText(String.valueOf(resultado));
                 
        }else if(comprimento1 == "Centimetro" && comprimento2 == "Decimetro"){
                
            resultado = valor1 / 0.1;
            result.setText(String.valueOf(resultado));
                 
        }else if(comprimento1 == "Centimetro" && comprimento2 == "Quilometro"){
                
            resultado = valor1 / 0.00001;
            result.setText(String.valueOf(resultado));
                 
        }else if(comprimento1 == "Centimetro" && comprimento2 == "Milimetro"){
                
            resultado = valor1 * 10;
            result.setText(String.valueOf(resultado));
            
        }else if(comprimento1 == "Centimetro" && comprimento2 == "Centimetro"){
            
            resultado = valor1 * 1;
            result.setText(String.valueOf(resultado));
        
        }else if(comprimento1 == "Milimetro" && comprimento2 == "Metro"){
                
            resultado = valor1 / 0.001;
            result.setText(String.valueOf(resultado));
                 
        }else if(comprimento1 == "Milimetro" && comprimento2 == "Decimetro"){
                
            resultado = valor1 / 0.01;
            result.setText(String.valueOf(resultado));
                 
        }else if(comprimento1 == "Milimetro" && comprimento2 == "Centimetro"){
                
            resultado = valor1 / 0.1;
            result.setText(String.valueOf(resultado));
                 
        }else if(comprimento1 == "Milimetro" && comprimento2 == "Quilometro"){
                
            resultado = valor1 / 0.000001;
            result.setText(String.valueOf(resultado));
                 
        }else if(comprimento1 == "Milimetro" && comprimento2 == "Milimetro"){
            
            resultado = valor1 * 1;
            result.setText(String.valueOf(resultado));
        
        }
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        jComboBox3.setSelectedItem("Quilometro");
        jComboBox3.setSelectedItem("Metro");
        jComboBox3.setSelectedItem("Decimetro");
        jComboBox3.setSelectedItem("Centimetro");
        jComboBox3.setSelectedItem("Miliemtro");        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        jComboBox4.setSelectedItem("Quilometro");
        jComboBox4.setSelectedItem("Metro");
        jComboBox4.setSelectedItem("Decimetro");
        jComboBox4.setSelectedItem("Centimetro");
        jComboBox4.setSelectedItem("Milimetro");
        
    }//GEN-LAST:event_jComboBox4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField result;
    // End of variables declaration//GEN-END:variables
}
